version: '3.8'

networks:
  app_net:
    driver: bridge
    
services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-api.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_net

  # Frontend React App
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_URL=http://localhost/api
    depends_on:
      - backend
    networks:
      - app_net

  # Backend API Server (you need to create this)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bandmate_harmony
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - app_net

  # PostgreSQL Database
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bandmate_harmony
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app_net

volumes:
  db_data:
