version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000" # adjust if your app uses a different port
    environment:
      # Change these to match your app's needs
      DATABASE_URL: postgres://postgres:postgres@db:5432/bandmate
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bandmate
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
