import { Strumento } from '@/types';

export const STRUMENTI: Strumento[] = [
  'Voce',
  'Flauto',
  'Ottavino',
  'Oboe',
  'Corno Inglese',
  'Fagotto',
  'Controfagotto',
  'Clarinetto Mib',
  'Clarinetto Sib',
  'Clarinetto Contralto',
  'Clarinetto Basso in Sib',
  'Clarinetto Contrabbasso',
  'Sassofono Soprano',
  'Sassofono Contralto',
  'Sassofono Tenore',
  'Sassofono Baritono',
  'Sassofono Basso',
  'Tromba',
  'Trombino',
  'Tromba bassa',
  'Cornetta',
  'Flicorno Soprano',
  'Flicorno contralto',
  'Flicorno tenore',
  'Flicorno baritono',
  'Corno',
  'Trombone Tenore',
  'Trombone Basso',
  'Basso Tuba',
  'Rullante',
  'Cassa',
  'Piatti',
  'Tastiere a percussione',
  'Batteria',
  'Percussioni varie',
  'Pianoforte',
  'Chitarra',
  'Basso elettrico',
  'Altro',
];
