// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amexkcpdvqauykpklocd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtZXhrY3BkdnFhdXlrcGtsb2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTIxMTIsImV4cCI6MjA2NDc4ODExMn0.WUE1De9u14FwS3lIIESsFoMzGIf9A-YTxICepzUdv4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);